# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sJY6g1HoG6mQlC6HU1OU5_W62bucdohn
"""

import numpy as np
import pandas as pd
from google.colab import drive

prefix = '/content/drive'
from google.colab import drive
drive.mount(prefix, force_remount=True)

a_path = '/content/drive/My Drive/550 project/Airbnb_Data.csv'

ycheckin_path = '/content/drive/My Drive/550 project/yelp_academic_dataset_checkin.csv'
'''1'''
yuser_path = '/content/drive/My Drive/550 project/yelp_academic_dataset_user.csv'
'''1'''
ytip_path = '/content/drive/My Drive/550 project/yelp_academic_dataset_tip.csv'
'''1'''
ybus_path = '/content/drive/My Drive/550 project/yelp_academic_dataset_business.csv'
yrev_path = '/content/drive/My Drive/550 project/yelp_academic_dataset_review.csv'

'''CREATE TABLE user (
    user_id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    review_count INT,
    fans INT,
    average_stars DECIMAL(2,1),
    compliment_useful INT
);
'''


'''CREATE TABLE review_business (
    review_id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,
    business_id VARCHAR(255) NOT NULL,
    stars DECIMAL(2,1),
    date DATE,
    text TEXT,
    useful INT,
    FOREIGN KEY (user_id) REFERENCES user(user_id),
    FOREIGN KEY (business_id) REFERENCES business(business_id)
);'''


'''CREATE TABLE tip_business (
    user_id VARCHAR(255) NOT NULL,
    business_id VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    text TEXT,
    useful INT,
    FOREIGN KEY (user_id) REFERENCES user(user_id),
    FOREIGN KEY (business_id) REFERENCES business(business_id),
    PRIMARY KEY (user_id, business_id, date)
);'''

u_df = pd.read_csv(yuser_path)
print(u_df.head())

print(u_df.columns.tolist())

u_kept_col=['user_id', 'name', 'review_count', 'fans', 'average_stars', 'useful']
u_ori_col=['user_id', 'name', 'review_count', 'yelping_since', 'useful', 'funny', 'cool', 'elite', 'friends', 'fans', 'average_stars', 'compliment_hot', 'compliment_more', 'compliment_profile', 'compliment_cute', 'compliment_list', 'compliment_note', 'compliment_plain', 'compliment_cool', 'compliment_funny', 'compliment_writer', 'compliment_photos']

u_df = u_df.loc[:, u_kept_col]

u_df

u_df = u_df.dropna(subset=['user_id'])
u_df

u_df = u_df.replace('', np.nan)

u_df.to_csv('/content/drive/My Drive/550 project/cleaned_yuser.csv', index=False, encoding='utf-8')